name: "Yandex object storage static website"
description: "Deploy static website to Yandex Object Storage"
author: "Nikita"
inputs:
    access-key-id:
        description: "Service account access key id"
        default: ""
        required: true
    secret-access-key:
        description: "Service account secret access key"
        default: ""
        required: true
    bucket:
        description: "Bucket name"
        default: ""
        required: true
    include:
        description: "Include patterns for files"
        default: ""
        required: true
    exclude:
        description: "Exclude patterns for files"
        default: ""
        required: false
    clear:
        description: "Clear bucket before deploy"
        default: false
        required: false
runs:
    using: "node16"
    main: "dist/index.js"
branding:
    icon: "upload-cloud"
    color: "blue"
