name: Test itself

on:
    push:
        branches: [master]

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: ./
              with:
                  access-key-id: ${{ secrets.ACCESS_KEY_ID }}
                  secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
                  bucket: ${{ secrets.BUCKET }}
                  include: |
                      **/*
                  exclude: |
                      .gitignore
                      yarn.lock
                      node_modules/**
                  clear: true
